### ISSUE TITLE
Compilation on iOS fails

### ISSUE THREAD

**Issue by natete** [ModusCreateOrg/cordova-plugin-android-fingerprint-auth#1]
iOS is complaining about a the plugin because it doesn't find the implementation.

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
